import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { X, RefreshCw } from "lucide-react";
import { toast } from "sonner";

interface UpdateEquipmentModalProps {
  open: boolean;
  onClose: () => void;
  equipment: {
    id: string;
    inventoryName: string;
    serialNumber: string;
  } | null;
  availableInventory: Array<{
    id: string;
    name: string;
  }>;
  onUpdate?: (equipmentId: string, inventoryId: string, serialNumber: string) => void;
}

const UpdateEquipmentModal = ({
  open,
  onClose,
  equipment,
  availableInventory,
  onUpdate,
}: UpdateEquipmentModalProps) => {
  const [selectedInventoryId, setSelectedInventoryId] = useState<string>("");
  const [serialNumber, setSerialNumber] = useState<string>("");
  const [isSerialAutoGenerated, setIsSerialAutoGenerated] = useState<boolean>(false);

  // Pre-fill form when modal opens or equipment changes
  useEffect(() => {
    if (open && equipment) {
      // Find inventory ID by matching name
      const inventoryItem = availableInventory.find(
        item => item.name === equipment.inventoryName
      );
      setSelectedInventoryId(inventoryItem?.id || "");
      setSerialNumber(equipment.serialNumber);
      setIsSerialAutoGenerated(false);
    }
  }, [open, equipment, availableInventory]);

  const generateSerialNumber = () => {
    const prefix = "SN";
    const randomNum = Math.floor(1000 + Math.random() * 9000);
    const generated = `${prefix}-${randomNum}`;
    setSerialNumber(generated);
    setIsSerialAutoGenerated(true);
  };

  const handleSerialNumberChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSerialNumber(e.target.value);
    setIsSerialAutoGenerated(false);
  };

  const handleUpdate = () => {
    if (!equipment) {
      toast.error("Equipment not found");
      return;
    }

    if (!selectedInventoryId) {
      toast.error("Please select an inventory item");
      return;
    }

    if (!serialNumber.trim()) {
      toast.error("Please enter or generate a serial number");
      return;
    }

    if (onUpdate) {
      onUpdate(equipment.id, selectedInventoryId, serialNumber.trim());
    } else {
      // Mock update - in real app, this would call an API
      console.info("Updating equipment", {
        equipmentId: equipment.id,
        inventoryId: selectedInventoryId,
        serialNumber: serialNumber.trim(),
      });
      toast.success("Equipment updated successfully");
    }

    onClose();
  };

  const handleClose = () => {
    setSelectedInventoryId("");
    setSerialNumber("");
    setIsSerialAutoGenerated(false);
    onClose();
  };

  if (!equipment) return null;

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="w-[90%] max-w-sm mx-auto p-5 rounded-2xl shadow-lg bg-white [&>button]:hidden">
        <DialogDescription className="sr-only">
          Update equipment modal
        </DialogDescription>
        {/* Header */}
        <DialogHeader className="flex flex-row items-center justify-between pb-2 border-b border-gray-100">
          <DialogTitle className="text-lg font-semibold text-gray-800">Update Equipment</DialogTitle>
          <Button
            variant="ghost"
            size="icon"
            className="h-9 w-9 rounded-full hover:bg-gray-100"
            onClick={handleClose}
          >
            <X className="h-5 w-5 text-gray-600" />
          </Button>
        </DialogHeader>

        {/* Content */}
        <div className="space-y-4 mt-3">
          {/* Inventory Name Dropdown */}
          <div>
            <Label className="text-sm font-medium text-gray-700 mb-1 block">Inventory Name</Label>
            <Select value={selectedInventoryId} onValueChange={setSelectedInventoryId}>
              <SelectTrigger className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-1 focus:ring-orange-500 focus:border-orange-500">
                <SelectValue placeholder="Select Inventory" />
              </SelectTrigger>
              <SelectContent>
                {availableInventory.length === 0 ? (
                  <SelectItem value="no-items" disabled>
                    No inventory available
                  </SelectItem>
                ) : (
                  availableInventory.map((item) => (
                    <SelectItem key={item.id} value={item.id}>
                      {item.name}
                    </SelectItem>
                  ))
                )}
              </SelectContent>
            </Select>
          </div>

          {/* Serial Number / Product Code */}
          <div>
            <Label className="text-sm font-medium text-gray-700 mb-1 block">Serial Number / Product Code</Label>
            <div className="relative">
              <Input
                type="text"
                placeholder="Enter or auto-generate"
                value={serialNumber}
                onChange={handleSerialNumberChange}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm pr-10 focus:ring-1 focus:ring-orange-500 focus:border-orange-500"
              />
              <button
                onClick={generateSerialNumber}
                className="absolute right-2 top-1/2 transform -translate-y-1/2 text-gray-500 hover:text-orange-600 transition-colors"
                type="button"
              >
                <RefreshCw className="w-5 h-5" />
              </button>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex justify-end gap-2 pt-2 mt-4">
          <Button
            variant="outline"
            onClick={handleClose}
            className="rounded-lg text-gray-700 border-gray-300 hover:bg-gray-50"
          >
            Cancel
          </Button>
          <Button
            onClick={handleUpdate}
            className="ml-2 bg-orange-500 hover:bg-orange-600 text-white rounded-lg"
          >
            Update
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default UpdateEquipmentModal;



