import { useState, useRef, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import MobileHeader from "@/components/layout/MobileHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Upload, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { mockInventory } from "@/data/mobileMockData";

const EditInventoryItem = () => {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [isSkuAutoGenerated, setIsSkuAutoGenerated] = useState(false);
  const [formData, setFormData] = useState({
    name: "",
    inventoryType: "",
    price: "",
    itemUnit: "",
    sku: "",
    stockQuantity: "",
  });

  // Load inventory item data on mount
  useEffect(() => {
    if (id) {
      const inventoryItem = mockInventory.find(item => item.id === id);
      if (inventoryItem) {
        // Determine inventory type based on existing data
        // For now, defaulting to "fixed" if unitPrice exists, otherwise "variable"
        const inventoryType = inventoryItem.unitPrice ? "fixed" : "variable";
        
        setFormData({
          name: inventoryItem.name,
          inventoryType: inventoryType,
          price: inventoryItem.unitPrice ? inventoryItem.unitPrice.toString() : "",
          itemUnit: "",
          sku: inventoryItem.sku,
          stockQuantity: inventoryItem.stock.toString(),
        });
        setIsSkuAutoGenerated(false); // SKU is pre-filled, not auto-generated
      } else {
        toast.error("Inventory item not found");
        navigate("/inventory");
      }
    }
  }, [id, navigate]);

  const generateSKU = (itemName: string): string => {
    const trimmedName = itemName.trim() || "ITEM";
    const prefix = trimmedName.substring(0, 4).toUpperCase().replace(/\s/g, "");
    const random = Math.floor(1000 + Math.random() * 90000);
    return `${prefix}-${random}`;
  };

  const handleAutoGenerateSKU = () => {
    const generatedSKU = generateSKU(formData.name);
    setFormData({ ...formData, sku: generatedSKU });
    setIsSkuAutoGenerated(true);
  };

  // Auto-update SKU when Item Name changes (only if SKU was auto-generated)
  useEffect(() => {
    if (isSkuAutoGenerated && formData.name) {
      const generatedSKU = generateSKU(formData.name);
      setFormData(prev => ({ ...prev, sku: generatedSKU }));
    }
  }, [formData.name, isSkuAutoGenerated]);

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (file.type.startsWith("image/")) {
        const reader = new FileReader();
        reader.onloadend = () => {
          setImagePreview(reader.result as string);
        };
        reader.readAsDataURL(file);
      } else {
        toast.error("Please select an image file");
      }
    }
  };

  const handleSubmit = () => {
    if (!formData.name || !formData.sku || !formData.stockQuantity) {
      toast.error("Please fill in all required fields");
      return;
    }
    if (formData.inventoryType === "fixed" && !formData.price) {
      toast.error("Please enter price for Fixed inventory type");
      return;
    }
    if (formData.inventoryType === "unitPrice") {
      if (!formData.price) {
        toast.error("Please enter price for Unit Price inventory type");
        return;
      }
      if (!formData.itemUnit) {
        toast.error("Please enter item unit for Unit Price inventory type");
        return;
      }
    }
    // In real app, update inventory item: PUT /api/inventory/:id
    toast.success("Inventory updated successfully");
    navigate("/inventory");
  };

  return (
    <div className="h-full flex flex-col overflow-hidden bg-white">
      <MobileHeader title="Edit Inventory" showBack={true} />
      
      <div className="flex-1 overflow-y-auto scrollable pt-14 px-4 pb-6">
        <div className="p-4 space-y-4">
          {/* Upload Image */}
          <div className="flex flex-col items-center">
            <div className="relative w-20 h-20 rounded-full border-2 border-dashed border-gray-300 flex items-center justify-center overflow-hidden bg-gray-50 cursor-pointer hover:border-teal-400 transition-colors">
              {imagePreview ? (
                <img 
                  src={imagePreview} 
                  alt="Inventory preview" 
                  className="w-full h-full object-cover"
                />
              ) : (
                <div className="flex flex-col items-center justify-center">
                  <Upload className="h-5 w-5 text-gray-400 mb-1" />
                  <span className="text-gray-400 text-xs text-center">Upload</span>
                </div>
              )}
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                onChange={handleImageUpload}
                className="absolute inset-0 opacity-0 w-full h-full cursor-pointer"
              />
            </div>
          </div>

          {/* Item Name */}
          <div>
            <Label className="text-sm text-gray-700">Item Name *</Label>
            <Input
              type="text"
              placeholder="Item Name"
              value={formData.name}
              onChange={(e) => {
                setFormData({ ...formData, name: e.target.value });
              }}
              className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-1 focus:ring-teal-500 focus:border-teal-500 mt-1"
              required
            />
          </div>

          {/* Inventory Type Dropdown */}
          <div>
            <Label className="text-sm text-gray-700">Inventory Type</Label>
            <Select 
              value={formData.inventoryType} 
              onValueChange={(value) => setFormData({ ...formData, inventoryType: value, price: "", itemUnit: "" })}
            >
              <SelectTrigger className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-1 focus:ring-teal-500 focus:border-teal-500 mt-1">
                <SelectValue placeholder="Select inventory type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="fixed">Fixed</SelectItem>
                <SelectItem value="variable">Variable</SelectItem>
                <SelectItem value="unitPrice">Unit Price</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Price (visible when Fixed or Unit Price) */}
          {(formData.inventoryType === "fixed" || formData.inventoryType === "unitPrice") && (
            <div>
              <Label className="text-sm text-gray-600">$ Price</Label>
              <Input
                type="number"
                placeholder="0.00"
                step="0.01"
                min="0"
                value={formData.price}
                onChange={(e) => setFormData({ ...formData, price: e.target.value })}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-1 focus:ring-teal-500 focus:border-teal-500 mt-1"
              />
            </div>
          )}

          {/* Item Unit (visible only when Unit Price) */}
          {formData.inventoryType === "unitPrice" && (
            <div>
              <Label className="text-sm text-gray-600">Item Unit</Label>
              <Input
                type="text"
                placeholder="Item Unit"
                value={formData.itemUnit}
                onChange={(e) => setFormData({ ...formData, itemUnit: e.target.value })}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-1 focus:ring-teal-500 focus:border-teal-500 mt-1"
              />
            </div>
          )}

          {/* SKU */}
          <div>
            <Label className="text-sm text-gray-700">SKU *</Label>
            <div className="relative mt-1">
              <Input
                type="text"
                placeholder="SKU"
                value={formData.sku}
                onChange={(e) => {
                  setFormData({ ...formData, sku: e.target.value.toUpperCase() });
                  setIsSkuAutoGenerated(false);
                }}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 pr-10 text-sm focus:ring-1 focus:ring-teal-500 focus:border-teal-500"
                required
              />
              <button
                type="button"
                onClick={handleAutoGenerateSKU}
                className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-500 hover:text-teal-600 transition-colors p-1"
                title="Auto Generate SKU"
              >
                <RefreshCw className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Stock Quantity */}
          <div>
            <Label className="text-sm text-gray-700">Stock Quantity *</Label>
            <Input
              type="number"
              placeholder="Stock Quantity"
              min="0"
              value={formData.stockQuantity}
              onChange={(e) => setFormData({ ...formData, stockQuantity: e.target.value })}
              className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-1 focus:ring-teal-500 focus:border-teal-500 mt-1"
              required
            />
          </div>

          {/* Update Button */}
          <div className="flex justify-end mt-4">
            <Button
              onClick={handleSubmit}
              className="bg-teal-600 text-white rounded-full px-6 py-2 font-medium text-sm hover:bg-teal-700"
              disabled={!formData.name || !formData.sku || !formData.stockQuantity}
            >
              Update Inventory
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default EditInventoryItem;

